# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 00:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('camera', models.CharField(choices=[('Nikon', 'Nikon'), ('Minolta', 'Minolta'), ('Cannon', 'Cannon'), ('Polaroid', 'Polariod'), ('iPhoneX', 'iPhone X')], max_length=10)),
                ('services', multiselectfield.db.fields.MultiSelectField(choices=[('Wedding', 'Wedding'), ('SeniorPhotos', 'Senior Photos'), ('FamilyReunions', 'Family Reunions'), ('Birthdays', 'Birthdays'), ('Boudoir', 'Boudior')], max_length=20)),
                ('bio', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=10)),
                ('photo_style', multiselectfield.db.fields.MultiSelectField(choices=[('Matte', 'Matte Finish'), ('Glossy', 'Glossy Finish'), ('Poster', 'Poster Board'), ('Frameless', 'Frameless')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
