# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 21:41
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Wedding', 'Wedding'), ('SeniorPhotos', 'Senior Photos'), ('FamilyReunions', 'Family Reunions'), ('Birthdays', 'Birthdays'), ('Boudoir', 'Boudoir')], max_length=20),
        ),
    ]
