# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20171129_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera',
            field=models.CharField(blank=True, choices=[('Nikon', 'Nikon'), ('Minolta', 'Minolta'), ('Cannon', 'Cannon'), ('Polaroid', 'Polariod'), ('iPhoneX', 'iPhone X')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photo_style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Matte', 'Matte Finish'), ('Glossy', 'Glossy Finish'), ('Poster', 'Poster Board'), ('Frameless', 'Frameless')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Wedding', 'Wedding'), ('SeniorPhotos', 'Senior Photos'), ('FamilyReunions', 'Family Reunions'), ('Birthdays', 'Birthdays'), ('Boudoir', 'Boudoir')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='website',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
